class node_c:
    # player: str

    def __init__ (self, player, state):
        self.player = player
        self.state = state

class extensive_form_c:
    # action: -- not just str
    #   we need structured data to encode action

    # succ: (node, action) -> node
    # - succ is assumed to be injective
    #   so the graph generated by it is a tree

    # pure_utility: leaf -> payoff_series

    def __init__ (self, succ):
        self.succ = succ

# backward induction
# minmax
